### ISSUE TITLE
Problems with building & applying kernels.

### ISSUE THREAD

**Issue by CCano8** [dgist-datalab/trace_generator#10]
Hi,

I'm trying to build and install the Linux kernel for physical traces, and I'm currently setting up an environment on a QEMU VM. As you mentioned, I tried to create an Ubuntu 20.04.5 LTS with Linux Kernel 5.17.4 installed OS.

Initially, due to dependency problems, I copied the ubuntu_defconfig file from the kernel files and ran "make bindeb-pkg -j64" on another server with Ubuntu 22.04. The kernel was successfully built, but using "dpkg" on Ubuntu 20.04.5 LTS resulted in kernel panics.

Upon checking the kernel version of Ubuntu 20.04.5 LTS, I found that the default installed kernel is 5.4.0-144-generic. So, I attempted to install kernel 5.17.5 with sudo dpkg -i *.deb (since I couldn't find original deb files with 5.17.4), but I encountered libc6 and libssl3 package errors, which require upgrading Ubuntu to 22.04 LTS.

Could you please provide more detailed guidance on creating this environment, or let me know if there are any additional steps or considerations I might be missing?

Thank you for your help.

**Comment by arter97** [comment]
> Hi,
> 
> I'm trying to build and install the Linux kernel for physical traces, and I'm currently setting up an environment on a QEMU VM. As you mentioned, I tried to create an Ubuntu 20.04.5 LTS with Linux Kernel 5.17.4 installed OS.
> 
> Initially, due to dependency problems, I copied the ubuntu_defconfig file from the kernel files and ran "make bindeb-pkg -j64" on another server with Ubuntu 22.04. The kernel was successfully built, but using "dpkg" on Ubuntu 20.04.5 LTS resulted in kernel panics.

It shouldn't. Please post the panic log (even as a camera shot) here so that we can assist you further.

> 
> Upon checking the kernel version of Ubuntu 20.04.5 LTS, I found that the default installed kernel is 5.4.0-144-generic. So, I attempted to install kernel 5.17.5 with sudo dpkg -i *.deb (since I couldn't find original deb files with 5.17.4), but I encountered libc6 and libssl3 package errors, which require upgrading Ubuntu to 22.04 LTS.

You can just install the image.deb file and nothing else. That wouldn't have a libc6/libssl3 dependency errors.
And what do you mean by 5.17.5/5.17.4 files? Are you trying to install kernel packages from mainline PPA?

> 
> Could you please provide more detailed guidance on creating this environment, or let me know if there are any additional steps or considerations I might be missing?
> 
> Thank you for your help.

**Comment by CCano8** [comment]
Thank you for your response. I would like to mention that I have limited knowledge and experience about the kernel, so my questions might be a bit off. I appreciate your patience and understanding.

> You can just install the image.deb file and nothing else. That wouldn't have a libc6/libssl3 dependency errors.
And what do you mean by 5.17.5/5.17.4 files? Are you trying to install kernel packages from mainline PPA?

To clarify, do you mean that the CXL-kernel can be applied regardless of the kernel version the system is using? Should I simply apply the .debs on Ubuntu 20.04.5 LTS with the 5.4.0-144 kernel?

Initially, I thought the steps were:
1. Setup Ubuntu 20.04.5 LTS
2. Change the kernel to 5.17.4
3. Build the CXL-kernel from "https://github.com/dgist-datalab/cxl-kernel.git"
4. Run `make bindeb-pkg` and install the .deb packages with `dpkg`

Is this understanding correct?

> It shouldn't. Please post the panic log (even as a camera shot) here so that we can assist you further.

Regarding this part, I might have made some mistakes while applying the kernel. If the issue persists, I will post the panic log here for further assistance.

Thank you again for your help.

**Comment by arter97** [comment]
> Thank you for your response. Before diving into the details, I would like to mention that I have limited knowledge and experience about the kernel, so my questions might be a bit off. I appreciate your patience and understanding.
> 
> > You can just install the image.deb file and nothing else. That wouldn't have a libc6/libssl3 dependency errors.
> > And what do you mean by 5.17.5/5.17.4 files? Are you trying to install kernel packages from mainline PPA?
> 
> To clarify, do you mean that the CXL-kernel can be applied regardless of the kernel version the system is using? Should I simply apply the .debs on Ubuntu 20.04.5 LTS with the 5.4.0-144 kernel?

Kernels almost always provide backward-compatibility to the userspace. I've personally ran 20.04's kernel on 12.04.
(There are some variables and annoyances like initramfs, headers needing newer versions of glibc, etc)

> 
> Initially, I thought the steps were:
> 
> 1. Setup Ubuntu 20.04.5 LTS
> 2. Change the kernel to 5.17.4

You don't need this step.

> 3. Build the CXL-kernel from "https://github.com/dgist-datalab/cxl-kernel.git"
> 4. Run `make bindeb-pkg` and install the .deb packages with `dpkg`
> 
> Is this understanding correct?

Yes except you most definitely don't need step 2.

Also, if you build a deb package from 22.04, some of the header files will dynamically link against the system libraries used in Ubuntu 22.04, which includes glibc. While the kernel itself will boot (from the image.deb), use of kernel headers like using dkms may be broken. I suggest you to try matching the compile machine and target machine's Ubuntu version.

> 
> > It shouldn't. Please post the panic log (even as a camera shot) here so that we can assist you further.
> 
> Regarding this part, I might have made some mistakes while applying the kernel. If the issue persists, I will post the panic log here for further assistance.
> 
> Thank you again for your help.

**Comment by CCano8** [comment]
Thank you for your explanation. It seems that I had some misunderstandings.

>>3. Build the CXL-kernel from "https://github.com/dgist-datalab/cxl-kernel.git"
>>4. Run make bindeb-pkg and install the .deb packages with dpkg
>>Is this understanding correct?
>Yes except you most definitely don't need step 2.

So I'm simply making cxl-kernel on ubuntu20.04 and using dpkg as you explained.

However, "make bindeb-pkg -j64" gives some errors like

![image](https://github.com/user-attachments/assets/cd86f06b-8614-4cf6-9f88-8f0f8ff1af4e)

Do I just need to fix some declarations and apply with dpkg? Is there something I might be missing?

**Comment by CCano8** [comment]
Successfully installed the kernel, and it is working properly. 
Thanks for your help!
