### ISSUE TITLE
Is it possible to run cxl-kernel in virtual env?

### ISSUE THREAD

**Issue by Halifuda** [dgist-datalab/trace_generator#4]
Hi! It seems like the cxl-kernel is required to be installed. Is it possible to run it virtually like in `qemu` or `docker`? I have no my personal machine so I'm not expected to modify the original installed kernel. Thank you!

**Comment by ZYFZYF** [comment]
same question

**Comment by arter97** [comment]
Hi,

The trace generator requires the corresponding kernel modifications to be in place, so this will be a bit hard to run under a container setup like Docker.

A virtual machine like QEMU will do the job, and it is in fact what we internally used for a time to validate our tools.

Simply just install a Linux distro under QEMU (libvirt or virt-manager is recommended) and install the kernel like any other.
There's nothing inherently blocks the trace generator or our modified kernel to run under a virtualized environment.

Hope this helps.
Let me know if you have further questions regarding the kernel setup.
