### ISSUE TITLE
Error in installing linux kernel

### ISSUE THREAD

**Issue by ghost** [dgist-datalab/trace_generator#7]
Can you please specify the command that needs to be entered to successfully install the linux kernel?

**Comment by arter97** [comment]
The "Linux Kernel" section lays out how to build and install the Linux kernel with specific commands, and it's the standard process that all debian-based Linux distros follow.

Please elaborate with more details if you are encountering issues.

**Comment by yorozuya4** [comment]
When building and installing the linux kernel, I have encountered an error that .config is missing, so I set a default .config and continued the process of installation. When I rebooted, I encountered an error message that says: "Failed to reboot system via logind: Interactive authentication required. Failed to open initctl fifo: Permission denied, Failed to talk to init daemon", which indicates that the modified kernel for CXL has not been loaded properly. Would you please help me fix this issue?

**Comment by arter97** [comment]
Ah, it's defconfig issue.

See https://github.com/dgist-datalab/trace_generator/commit/42d8f70135bb91b266229eb3247e20955762a2be and try if it fixes your issue.
