### ISSUE TITLE
Error in installing linux kernel

### ISSUE THREAD

**Issue by ghost** [dgist-datalab/trace_generator#8]
When building and installing the linux kernel for trace generator, I have encountered an error that .config is missing, so I set a default .config and continued the process of installation. When I rebooted, I encountered an error message that says: "Failed to reboot system via logind: Interactive authentication required. Failed to open initctl fifo: Permission denied, Failed to talk to init daemon", which indicates that the modified kernel for CXL has not been loaded properly. Would you please help me fix this issue?

**Comment by arter97** [comment]
Fixed with 42d8f70135bb91b266229eb3247e20955762a2be
